In [2]:
import pandas as pd

df = pd.read_csv("../../data/guide_box.csv")
df

     x1   y1   x2   y2  label
0   411  190  538  375      0
1   411  190  538  375      1
2   411  190  538  375      2
3   411  190  538  375      3
4   385  260  526  359      4
5   369  264  548  422      5
6   375  273  552  416      6
7   332  289  507  428      7
8   345  277  520  418      8
9   411  190  538  375      9
10  411  190  538  375     10
11  351  170  489  284     11
12   79  310  218  438     12
13  396  310  536  438     12
14   79  310  218  438     13
15  396  310  536  438     13
16  260  222  333  325     14
17  252  272  342  380     15
18  269  264  321  423     16
19  320  218  406  366     17
20  270  242  365  393     18
21  203  389  368  448     19
22  268  243  348  387     19
23  273  309  443  394     20
24  198  378  376  441     20
25  329  224  421  310     21
26  311  239  396  321     22
27  228  236  309  319     22
28  270  223  343  343     23
29  262  263  401  349     24
30  228  110  372  289     25

In [ ]:
# 기존 해상도 정보
initial_width, initial_height, = 640, 480

# 비율 계산(0.0~1.0)
df["x1_ratio"] = df["x1"] / initial_width
df["y1_ratio"] = df["y1"] / initial_height
df["x2_ratio"] = df["x2"] / initial_width
df["y2_ratio"] = df["y2"] / initial_height

In [6]:
new_df = df.drop(["x1", "y1", "x2", "y2"], axis=1)
new_df
new_df.to_csv("../../data/guide_box_ratio.csv", index=False)

In [ ]:
# 새로운 좌표 계산

     x1   y1   x2   y2  label  x1_ratio  y1_ratio  x2_ratio  y2_ratio
0   411  190  538  375      0  0.642188  0.395833  0.840625  0.781250
1   411  190  538  375      1  0.642188  0.395833  0.840625  0.781250
2   411  190  538  375      2  0.642188  0.395833  0.840625  0.781250
3   411  190  538  375      3  0.642188  0.395833  0.840625  0.781250
4   385  260  526  359      4  0.601562  0.541667  0.821875  0.747917
5   369  264  548  422      5  0.576562  0.550000  0.856250  0.879167
6   375  273  552  416      6  0.585938  0.568750  0.862500  0.866667
7   332  289  507  428      7  0.518750  0.602083  0.792188  0.891667
8   345  277  520  418      8  0.539062  0.577083  0.812500  0.870833
9   411  190  538  375      9  0.642188  0.395833  0.840625  0.781250
10  411  190  538  375     10  0.642188  0.395833  0.840625  0.781250
11  351  170  489  284     11  0.548438  0.354167  0.764062  0.591667
12   79  310  218  438     12  0.123438  0.645833  0.340625  0.912500
13  396  310  536  438     12  0.618750  0.645833  0.837500  0.912500
14   79  310  218  438     13  0.123438  0.645833  0.340625  0.912500
15  396  310  536  438     13  0.618750  0.645833  0.837500  0.912500
16  260  222  333  325     14  0.406250  0.462500  0.520312  0.677083
17  252  272  342  380     15  0.393750  0.566667  0.534375  0.791667
18  269  264  321  423     16  0.420312  0.550000  0.501563  0.881250
19  320  218  406  366     17  0.500000  0.454167  0.634375  0.762500
20  270  242  365  393     18  0.421875  0.504167  0.570312  0.818750
21  203  389  368  448     19  0.317188  0.810417  0.575000  0.933333
22  268  243  348  387     19  0.418750  0.506250  0.543750  0.806250
23  273  309  443  394     20  0.426563  0.643750  0.692187  0.820833
24  198  378  376  441     20  0.309375  0.787500  0.587500  0.918750
25  329  224  421  310     21  0.514062  0.466667  0.657813  0.645833
26  311  239  396  321     22  0.485938  0.497917  0.618750  0.668750
27  228  236  309  319     22  0.356250  0.491667  0.482812  0.664583
28  270  223  343  343     23  0.421875  0.464583  0.535937  0.714583
29  262  263  401  349     24  0.409375  0.547917  0.626563  0.727083
30  228  110  372  289     25  0.356250  0.229167  0.581250  0.602083